{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      substituters = [
        "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store"
      ];
      trusted-public-keys = [
        "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      ];
    };
  };
  users.users.sdhou = {
    uid = 501;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/sdhou";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;
  services.redis.servers."myredis" = {
    enable = true;
    port = 6379;
    bind = "0.0.0.0";
    openFirewall = true;
  };
  services.postgresql = {
    enable = true;
    enableTCPIP = true;
    package = pkgs.postgresql_17;
    initialScript = pkgs.writeText "init.sql" ''
      CREATE ROLE oye WITH LOGIN PASSWORD 'mypassword';
      CREATE DATABASE oyedb OWNER oye;
    '';
    settings = {
      listen_addresses = "*";
      port = 5432;
    };
  };
  services.nginx = {
    enable = true;
    virtualHosts."loclahost" = {
      root = "/var/www/html";
      listen = [ { addr = "0.0.0.0"; port = 8000; } ];
      default = true;
    };
  };
  services.minio = {
    enable = true;  # 启用 MinIO 服务
    listenAddress = "0.0.0.0:9000";  # 监听地址和端口，设置为 0.0.0.0:9000 表示监听所有接口
    consoleAddress = "0.0.0.0:9001";  # Web 控制台地址和端口
    region = "us-east-1";  # 设置 MinIO 的区域，默认为 us-east-1
    dataDir = ["/var/lib/minio/data"];  # 数据存储目录，可以指定多个路径
    rootCredentialsFile = "/etc/nixos/minio-credentials";  # 根用户凭据文件路径
    browser = true;  # 启用 Web UI
  };

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Shanghai";
  i18n.defaultLocale = "zh_CN.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ALL = "zh_CN.UTF-8";
    LANG = "zh_CN.UTF-8";
    LC_CTYPE = "zh_CN.UTF-8";
  };

  # 安装中文字体
  fonts = {
    enableDefaultPackages = true; # 启用默认字体
    packages = with pkgs; [
      noto-fonts        # Google Noto 字体，支持多种语言
      noto-fonts-cjk-sans    # 中日韩字体
      wqy_zenhei        # 文泉驿正黑字体
      wqy_microhei      # 文泉驿微米黑字体
    ];
    fontconfig = {
      defaultFonts = {
        sansSerif = [ "Noto Sans CJK SC" ];
        serif = [ "Noto Serif CJK SC" ];
        monospace = [ "Noto Sans Mono CJK SC" ];
      };
    };
  };

  # 确保终端支持 UTF-8
  console = {
    font = "Lat2-Terminus16";
    useXkbConfig = true; # 使用 X11 的键盘布局（可选）
  };

  environment.systemPackages = with pkgs; [
    axel      # 多线程下载工具
    bat       # cat 的增强版
    cloc      # 代码统计工具
    go        # Go 编程语言
    git       # 版本控制工具
    htop      # 系统监控工具
    jdk       # Java 开发工具包
    jq        # JSON 处理工具
    postgresql # PostgreSQL 数据库
    minio     # 对象存储服务
    minio-client
    mycli     # MySQL 客户端
    maven     # Java 项目管理工具
    nginx     # Web 服务器
    nodejs    # Node.js
    pnpm      # 包管理器
    pm2       # Node.js 进程管理
    vim       # 文本编辑器
    wget      # 下载工具
    tree      # 目录树查看工具
    unzip     # 解压工具
    redis     # Redis 数据库
    yarn      # 包管理器
    rclone    # 云存储同步工具
    wrk       # HTTP 基准测试工具
    tig       # Git 交互式查看工具
  ];
  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIICDTCCAbKgAwIBAgIQFr+cbyOGzIg7NBsDMSE/jTAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTIzMTEyMTAzMjAxMloXDTMzMTEyMTAzMjAxMlowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABEPrv1PpSrlsCErKVz4Xsq0wz2bhbDdBLa9e
DI8Y+lZ36DWmrz0mAPyou6gev0/mmkKMwjZb6RCKYEkifD31fQ+jQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR7Tx3U6Wlg4WsH
LSWgRowXo9dr1zAKBggqhkjOPQQDAgNJADBGAiEAnUEbat8fbblX+0nPzLvt8aKy
r+QFDq54SrzRCJRiZ0MCIQCOmvSN+ymRlX/qmqpHp+tacd2KG07HS00R8yTzN0uK
nw==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIGdzCCBF+gAwIBAgIJAPdh8KAqpGN5MA0GCSqGSIb3DQEBBQUAMIGKMQswCQYD
VQQGEwJDTjEOMAwGA1UECAwFSHVuYW4xETAPBgNVBAcMCENoYW5nc2hhMQwwCgYD
VQQKDANJVC0xDzANBgNVBAsMBklULU9yZzESMBAGA1UEAwwJbG9jYWxob3N0MSUw
IwYJKoZIhvcNAQkBFhZzdXBwb3J0X0lUQGV4YW1wbGUuY29tMB4XDTIxMDcwNzA2
NTM1M1oXDTMxMDcwNTA2NTM1M1owgYoxCzAJBgNVBAYTAkNOMQ4wDAYDVQQIDAVI
dW5hbjERMA8GA1UEBwwIQ2hhbmdzaGExDDAKBgNVBAoMA0lULTEPMA0GA1UECwwG
SVQtT3JnMRIwEAYDVQQDDAlsb2NhbGhvc3QxJTAjBgkqhkiG9w0BCQEWFnN1cHBv
cnRfSVRAZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
AQC6JyvhVcgwYtjwO9NwRvPQxr7V2IvGFas1ix7peHAbZCbTnAoXFs4RpODMbt++
mKmJTO0DOIRbowMn0zcCOJVQnybzZ6i+suXNsAWBIx4ZryiAXpk3YLWhw9X0UIxs
XdbS/lUrHweBkgSFk2uuV7V/BFDIRxEs0khQHoeoSZZDM5O05JdxEhwhG5k9O/f9
Z4pQ7B4f+0kFlyJqs5OR0MMDI95e9YYyd1z9efKOtA/hjFpBHyGUcHiYzv0AoE94
NwvSwMsHXwHaH0so8VcxFDXoQIIuHkSMMXe6oixiQbILuiiqChBByJJ6Ucc5JOx/
FqDS9uq+asGO+02L4phWB5jwDc6tp/0OEyC7uj9rVcy+0nnvfO6eIFyAU4cZP1Ls
VfIDERqNci6VPpKPh5PrxBxLNOYvqPwoMNz32tVYot5a/qBv0SjlgsWmGyNybBOD
f9zQWPRMezfap7r9nhX6f47GdimwwCTKUVBxKU09fGJj3zpPqY21QWEHAnkzjY6u
8llUP/+QWC7T5UQj8tBU+RRZAVPT+Siu1yIm49zPKAirZBHQsoYeMo/hJDTKCSb/
2LNXNxCWAfZSvdhBZIdFmCUcxhIRddMllolMa3uNGqaEUIlZrPeYEC6WixmBRaGE
6zqKlSM8Ra8qrZefbZNyZFXOlVMJvU7FzfXDmxV0NqBXpwIDAQABo4HdMIHaMIGp
BgNVHSMEgaEwgZ6hgZCkgY0wgYoxCzAJBgNVBAYTAkNOMQ4wDAYDVQQIDAVIdW5h
bjERMA8GA1UEBwwIQ2hhbmdzaGExDDAKBgNVBAoMA0lULTEPMA0GA1UECwwGSVQt
T3JnMRIwEAYDVQQDDAlsb2NhbGhvc3QxJTAjBgkqhkiG9w0BCQEWFnN1cHBvcnRf
SVRAZXhhbXBsZS5jb22CCQCFZPuRbM47MDAJBgNVHRMEAjAAMAsGA1UdDwQEAwIE
8DAUBgNVHREEDTALgglsb2NhbGhvc3QwDQYJKoZIhvcNAQEFBQADggIBAI0m9gAe
NWbLbBnFeGDUAoLlsVK6wkJWip4a/7syHH3/2wpxjw7eO4KcaiUrngXj+ElDeqRY
+uB8N2Kk2ej2dddWVImsHx4DNNq4kHyAp8+7+/2ltKI2aYRYSdO9OZ1NUH/YWYYK
MfyISW3n+ynGyC9vCQkIhWDimcLC/eF+u5uI7g9c2cuiSoX5Fap3DW6viFd2mvTS
xH2KO/3ExZLBoaRUSTgk08Dbo1QTGo7XXidykCx6cmbxkHPxZDsOVMeoZeh/Gjq+
/+3akVCDzfNVvMe9dNV/a2qZ+GI6b1mYG8yU09nuj6Bf4se+5uI/cmB0xtQU68pu
fm/G3lpNNxe+gxiBrYprDRq85Ks9bBD2Rkd4PsS9f8MGyQHSibV6K1vE+8lYW17B
J+G8lDADZclxkbfppU9ml5iNoV15S5MOZCVRoNGIZxK8eE5ON2KJD0+4vRRcdNIB
j8gdObc6m6qvYBdoQL4xxzNt0OsgBWNS/iRTANazBRs60XVkVJkMGQHWb3Dd2d2d
0y2el2qOC0VMgX+jxkpxAqQ6dFKt/OG3WYuyyIIeJTcm5vASOJkaRZaz3o+7i86e
nYISGJ3vReMAutHea5DQP+K0LLcU7UHicVMF6QHcS4PPZbGhMnQtGO2x3Z83AU3W
2KxqW8zvyZdsFIYn3GPBSM9BsiOEeWvMYmYQ
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIID1jCCAr6gAwIBAgIDBNR4MA0GCSqGSIb3DQEBCwUAMIGSMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKQ2FsaWZvcm5pYTEPMA0GA1UEBwwGSXJ2aW5lMR8wHQYDVQQK
DBZCbGl6emFyZCBFbnRlcnRhaW5tZW50MRMwEQYDVQQLDApCYXR0bGUubmV0MScw
JQYDVQQDDB5CbGl6emFyZCBCYXR0bGUubmV0IExvY2FsIENlcnQwHhcNMjIwOTIw
MDUxMTAyWhcNMzIwOTE3MDUxMTAyWjCBkjELMAkGA1UEBhMCVVMxEzARBgNVBAgM
CkNhbGlmb3JuaWExDzANBgNVBAcMBklydmluZTEfMB0GA1UECgwWQmxpenphcmQg
RW50ZXJ0YWlubWVudDETMBEGA1UECwwKQmF0dGxlLm5ldDEnMCUGA1UEAwweQmxp
enphcmQgQmF0dGxlLm5ldCBMb2NhbCBDZXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAzkW6h4GXa8t95RMbegDObWP29iXF8VlkTS25dLRBUCVgnY8X
0s9GQgW0VfU6DnlHqEBCpMci69ln3Mm0ir+XDw6TKn9tUPAF3RyyfrVpJfFKt+OE
NBEAr6005cAckc/3d3OkpZHctqQ8qL+9v1bx+VD8IQbHvzwa1h1leUikwwgs3DpJ
kvofIfy21wSIIE6V8W/Msqu2AJTmEhBVxvgCl+WeIdNmJjVpQpDk0UDvaHokDT3+
7SR96sB/nZ1Qoo0I3f48YoG9fByT7A5/zWpIP0B7hWNlNBcML1ddGQIoUQC3T0t+
zt+cqDT4ax6GePy43Ja1yvTB1XHIRWqX3zn62QIDAQABozMwMTATBgNVHSUEDDAK
BggrBgEFBQcDATAaBgNVHREEEzARgg9sb2NhbGJhdHRsZS5uZXQwDQYJKoZIhvcN
AQELBQADggEBAJnrgDQFnmUTPfY9ct7xLdG8tLnoxfimwk5y93uEHXwz4irVGxh0
WodWqEQxR3qH8c4Q5B4AHieT286tYQ52pXUfFrif8iXEpB8sbk9ynXpW5A/AGGv4
NJSOVFrvH5qqVksJhhhaKPm4qsrFEVqQDkmnYBBAhNG3V3j0ss3LpJwzfOB+cFGy
GLNk9H63NmtWQ/oSQUR165sT4Pbws/nPvA4XzOJXF546UagX0iV+rSlveMmcCld0
o1L7h0sEgzO5jRivULcXk3PQ3L1FhjI/F48M/Dmv2aK6ZC6q+bY0IBLwbj7Jej2A
UOEEBN71RxuL83iRhGU7hl7Q3Kp6MQ1eyFY=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIJAN6k1fozz56eMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNV
BAYTAkNOMRIwEAYDVQQIEwlndWFuZ2RvbmcxETAPBgNVBAcTCHNoZW56aGVuMSIw
IAYDVQQKExlTYW5nZm9yIFRlY2hub2xvZ2llcyBJbmMuMSIwIAYDVQQLExlTYW5n
Zm9yIFRlY2hub2xvZ2llcyBJbmMuMCAXDTE3MDQyNzE1MjcxOVoYDzIxMTcwNDAz
MTUyNzE5WjB8MQswCQYDVQQGEwJDTjESMBAGA1UECBMJZ3Vhbmdkb25nMREwDwYD
VQQHEwhzaGVuemhlbjEiMCAGA1UEChMZU2FuZ2ZvciBUZWNobm9sb2dpZXMgSW5j
LjEiMCAGA1UECxMZU2FuZ2ZvciBUZWNobm9sb2dpZXMgSW5jLjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAOhIli3++Brs1tZznZFFW5FzRSV4zASWtBCg
X3CxK+OqfMDRu41d5+EbQVjp20PwuIZO9Ozg34AcliQNLaB2uRW8YWWhD/g915WJ
YcYPcEcNjcFDiZVJHMaWk8uYZSw8j6B8HSAjj88OVlFZznfQ95HcEDH0dtu4DxO3
6pZ8iQGxvxN+l2xaN3VM7ih0Qt3lP197ftmkZLgodGNOe/n7qVBM8pcRFTCXOqi/
wKLUhQ77WfBPiHW9zegnY2Mtlvk/s/Bmisv5gbRIPZDLkg9PJAPeQi6qhkHs89uN
/trltli/tK25xRrElAkr/j2RkA7YODXKPHI9F5YvwrY8T60Qh8MCAwEAAaOB4jCB
3zAdBgNVHQ4EFgQU3cTVlAH4e3VFV6i+XrOsRhu4urMwga8GA1UdIwSBpzCBpIAU
3cTVlAH4e3VFV6i+XrOsRhu4urOhgYCkfjB8MQswCQYDVQQGEwJDTjESMBAGA1UE
CBMJZ3Vhbmdkb25nMREwDwYDVQQHEwhzaGVuemhlbjEiMCAGA1UEChMZU2FuZ2Zv
ciBUZWNobm9sb2dpZXMgSW5jLjEiMCAGA1UECxMZU2FuZ2ZvciBUZWNobm9sb2dp
ZXMgSW5jLoIJAN6k1fozz56eMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
ggEBAJPVZg3O0bnEma3x3gdFd7Lw54LcfIeIifvR5p9M30ELZkAI3MS4z0rdXzU6
X8dTpvwyM12zcMv1PQFD0a8zYFrW6truILpUXiOJ1oHftv3N0o+WeRp5JgGmg/YP
vlvCTiwZwM//3Fx3fAo0AHhxPhrel4F4yKtVKYZWrScRC4855957i+Q4jzNFDQqY
W9rcUwj6DHeF/tLN2E8qwJm7zeaqnEXLK8OcMTfguDBdJe0cTrvLaMk0jON6ZZ+U
7jb5hjH3vKyF6YlVzYtvro66Ht8Csv6QnaGdG73UEpuxjvxvC/LjFAm+b/Ds9EDq
3lE2kA02228ATbXpGNfbzk6W3DI=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIBpDCCAUqgAwIBAgIRAOKiREtTpfI+rIbvb6b8EKYwCgYIKoZIzj0EAwIwMDEu
MCwGA1UEAxMlQ2FkZHkgTG9jYWwgQXV0aG9yaXR5IC0gMjAyMyBFQ0MgUm9vdDAe
Fw0yMzEyMTkwNjAwMTJaFw0zMzEwMjcwNjAwMTJaMDAxLjAsBgNVBAMTJUNhZGR5
IExvY2FsIEF1dGhvcml0eSAtIDIwMjMgRUNDIFJvb3QwWTATBgcqhkjOPQIBBggq
hkjOPQMBBwNCAAQunQz0xZldCmBph/8J7VkHfvtT8OzNf1iJGRtnqAezIMCnPri/
RUgwoK0ul74Y+86m30Jv9bx+3mHnLWagKd8Fo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUrxAtTZAJCSkS3+mVP5avdF5T
XqgwCgYIKoZIzj0EAwIDSAAwRQIhAMA1uDXSBd9MXNitMLuNBqPtWdNoVfuHfqPH
yQG3POQTAiB16HqVn1jpt6qMjkD4FIBbDxJ1WIDSR71E3IOarW4XWw==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDwzCCAqugAwIBAgIUFAnC6268dp/z1DR9E1UepiWgWzkwDQYJKoZIhvcNAQEL
BQAwcDELMAkGA1UEBhMCQ04xEjAQBgNVBAgMCUNob25ncWluZzESMBAGA1UEBwwJ
Q2hvbmdxaW5nMQ4wDAYDVQQKDAVnb3dhczEWMBQGA1UECwwNSVQgRGVwYXJ0bWVu
dDERMA8GA1UEAwwIZ293YXMuY24wIBcNMjQwMjE4MDIwOTI2WhgPMjEyNDAxMjUw
MjA5MjZaMHAxCzAJBgNVBAYTAkNOMRIwEAYDVQQIDAlDaG9uZ3FpbmcxEjAQBgNV
BAcMCUNob25ncWluZzEOMAwGA1UECgwFZ293YXMxFjAUBgNVBAsMDUlUIERlcGFy
dG1lbnQxETAPBgNVBAMMCGdvd2FzLmNuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEA3A7dt7eoqAaBxv2Npjo8Z7VkGvXT93jZfpgAuuNuQ5RLcnOnMzQC
CrrjPcLfsAMA0AIK3eUWsXXKSR9SZTJBLQRZCJHZ9AIPfA+58JVQPTjd8UIuQZJf
rDf6FjhPJTsLzcjTU+mT7t6lEimPEl2VWN9eXWqs9nkVrJtqLao6m1hoYfXOxRh6
96/WgBtPHcmjujryteBiSITVflDjx+YQzDGsbqw7fM52klMPd2+w/vmhJ4pxq6P7
Ni2OBvdXYDPIuLfPFFqG16arORjBkyNCJy19iOuh5LXh+EUX11wvbLwNgsTd8j9v
eBSD+4HUUNQhiXiXJbs7I7cdFYthvb609QIDAQABo1MwUTAdBgNVHQ4EFgQUdI8p
aY1A47rWCRvQKSTRCCk6FoMwHwYDVR0jBBgwFoAUdI8paY1A47rWCRvQKSTRCCk6
FoMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEArMCAfqidgXL7
cW5TAZTCqnUeKzbbqMJgk6iFsma8scMRsUXz9ZhF0UVf98376KvoJpy4vd81afbi
TehQ8wVBuKTtkHeh/MkXMWC/FU4HqSjtvxpic2+Or5dMjIrfa5VYPgzfqNaBIUh4
InD5lo8b/n5V+jdwX7RX9VYAKug6QZlCg5YSKIvgNRChb36JmrGcvsp5R0Vejnii
e3oowvgwikqm6XR6BEcRpPkztqcKST7jPFGHiXWsAqiibc+/plMW9qebhfMXEGhQ
5yVNeSxX2zqasZvP/fRy+3I5iVilxtKvJuVpPZ0UZzGS0CJ/lF67ntibktiPa3sR
D8HixYbEDg==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICDTCCAbKgAwIBAgIQFr+cbyOGzIg7NBsDMSE/jTAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTIzMTEyMTAzMjAxMloXDTMzMTEyMTAzMjAxMlowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABEPrv1PpSrlsCErKVz4Xsq0wz2bhbDdBLa9e
DI8Y+lZ36DWmrz0mAPyou6gev0/mmkKMwjZb6RCKYEkifD31fQ+jQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR7Tx3U6Wlg4WsH
LSWgRowXo9dr1zAKBggqhkjOPQQDAgNJADBGAiEAnUEbat8fbblX+0nPzLvt8aKy
r+QFDq54SrzRCJRiZ0MCIQCOmvSN+ymRlX/qmqpHp+tacd2KG07HS00R8yTzN0uK
nw==
-----END CERTIFICATE-----

    ''
  ];

  system.stateVersion = "24.11"; # Did you read the comment?
}

